---
- name: Add node-ip to kubelet unit file
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^ExecStart=/usr/bin/kubelet'
    line: "ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS --node-ip={{ ansible_host }}"

- name: Systemd reload
  shell: systemctl daemon-reload

- name: Kubelet restart
  shell: systemctl restart kubelet
