---
- name: Install arptables and ebtables
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - arptables
    - ebtables

- name: Disable nf_tables
  shell: "{{ item }}"
  with_items:
    - 'update-alternatives --set iptables /usr/sbin/iptables-legacy'
    - 'update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy'
    - 'update-alternatives --set arptables /usr/sbin/arptables-legacy'
    - 'update-alternatives --set ebtables /usr/sbin/ebtables-legacy'




