---
all:
  children:
    nodes:
      hosts:
        node1: { ansible_host: 192.168.5.10 }
        node2: { ansible_host: 192.168.5.11 }
    master_nodes:
      hosts:
        node1:
    worker_nodes:
      hosts:
        node2: