---
- name: Configure kubectl for use as 'admin user' - create .kube directory
  file:
    path: "/home/{{ admin_user_name }}/.kube"
    owner: "{{ admin_user_name }}"
    group: "{{ admin_user_name }}"
    state: directory
    mode: '0700'

- name: Configure kubectl for use as 'admin user' - copy config file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ admin_user_name }}/.kube/config"
    owner: "{{ admin_user_name }}"
    group: "{{ admin_user_name }}"
    mode: '0600'
    remote_src: yes