---

- name: Prepare K8S Cluster
  become: yes
  hosts: nodes
  roles:
    - { role:  swapoff,                     tags: swapoff }
    - { role:  docker,                      tags: docker }
    - { role:  disable_nf_tables,           tags: disable_nf_tables }
    - { role:  kubernetes_components,       tags: kubernetes_components }

